{
  "formatVersion": "1.1",
  "component": {
    "group": "net.msrandom",
    "module": "kotlin-class-extensions-plugin",
    "version": "1.0.11",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.1.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "kotlin-class-extensions-plugin-1.0.11.jar",
          "url": "kotlin-class-extensions-plugin-1.0.11.jar",
          "size": 90527,
          "sha512": "7840dffa18a0c303052ebc179d0bc05c044664d5f9d8f9aae44b3ab972e813c43a22460782ee6459bc58aec1522413b445aaeb31b028c5f8bd6d0e69b5e76068",
          "sha256": "83191115fe72511d869868490f36ef70dd54e32a3bddf6561d67d5e2a03ce407",
          "sha1": "1adf80b6ef6af58be63fa2cd5a18051e80f57607",
          "md5": "a05e51905265d51676afe9bbffaa64c4"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-compiler-embeddable",
          "version": {
            "requires": "2.1.0"
          }
        },
        {
          "group": "net.msrandom",
          "module": "class-extension-annotations",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "kotlin-class-extensions-plugin-1.0.11.jar",
          "url": "kotlin-class-extensions-plugin-1.0.11.jar",
          "size": 90527,
          "sha512": "7840dffa18a0c303052ebc179d0bc05c044664d5f9d8f9aae44b3ab972e813c43a22460782ee6459bc58aec1522413b445aaeb31b028c5f8bd6d0e69b5e76068",
          "sha256": "83191115fe72511d869868490f36ef70dd54e32a3bddf6561d67d5e2a03ce407",
          "sha1": "1adf80b6ef6af58be63fa2cd5a18051e80f57607",
          "md5": "a05e51905265d51676afe9bbffaa64c4"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "kotlin-class-extensions-plugin-1.0.11-sources.jar",
          "url": "kotlin-class-extensions-plugin-1.0.11-sources.jar",
          "size": 16918,
          "sha512": "8ad34beb3bbac6d0bec75ad475796c664b2258c354f3d4347d7c7aa2234e4f93214f57c02bc55743d046e7dc99b9d8af5d91ec84b9a2cfc6cc807a2116305979",
          "sha256": "026d44277f37b8c99dae6bb5696c544cb00c7480fd17b7358e6f51222d7041a3",
          "sha1": "4892ea9f3284457830bb8366540f13e1ddeb5638",
          "md5": "d77ad05ecc334efcf8790f19457f3c57"
        }
      ]
    }
  ]
}
