{
  "formatVersion": "1.1",
  "component": {
    "group": "net.msrandom",
    "module": "classpath-api-stubs",
    "version": "0.1.11-dust",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.1.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "classpath-api-stubs-0.1.11-dust.jar",
          "url": "classpath-api-stubs-0.1.11-dust.jar",
          "size": 74800,
          "sha512": "8f31524c918e43f9934c5a6c6c128898749ceec4a90a27688e50ce67c5753d80ba418970758efeeb435eac032dad3f3901f52432213068f65b0da465a7762962",
          "sha256": "30c48650c3f6919a6430b9024a1463023a74f60e4eb96b89e7ea1364e26970fc",
          "sha1": "81230cbb59b7c6fa6de4067cce8d79fdc839861e",
          "md5": "5ed1bed2942b148eb5e8b779f51bf16f"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.ow2.asm",
          "module": "asm-tree",
          "version": {
            "requires": "9.7.1"
          }
        }
      ],
      "files": [
        {
          "name": "classpath-api-stubs-0.1.11-dust.jar",
          "url": "classpath-api-stubs-0.1.11-dust.jar",
          "size": 74800,
          "sha512": "8f31524c918e43f9934c5a6c6c128898749ceec4a90a27688e50ce67c5753d80ba418970758efeeb435eac032dad3f3901f52432213068f65b0da465a7762962",
          "sha256": "30c48650c3f6919a6430b9024a1463023a74f60e4eb96b89e7ea1364e26970fc",
          "sha1": "81230cbb59b7c6fa6de4067cce8d79fdc839861e",
          "md5": "5ed1bed2942b148eb5e8b779f51bf16f"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "classpath-api-stubs-0.1.11-dust-sources.jar",
          "url": "classpath-api-stubs-0.1.11-dust-sources.jar",
          "size": 12301,
          "sha512": "0e4499cc4cb5249296018876d818ffc6974cc1074f441a77cf400ed79e4bb13b5968b27a5256c998b1d13cf3de2514f4093a30872aa247f09c5ac9337ee93684",
          "sha256": "6a7fab3fdf30d15d89f2349a719538087c0f143bb54fc83d1ac0711e797ff1b8",
          "sha1": "c6339a9be8002a3c89a3c7c2704ab8e091c3e34b",
          "md5": "3dca3f87050df66e69d39e02f49727ac"
        }
      ]
    }
  ]
}
