{
  "formatVersion": "1.1",
  "component": {
    "group": "net.msrandom",
    "module": "classpath-api-stubs",
    "version": "0.1.10-dust",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.1.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "classpath-api-stubs-0.1.10-dust.jar",
          "url": "classpath-api-stubs-0.1.10-dust.jar",
          "size": 74942,
          "sha512": "02f82b0a76a7c7e240004bdeaf458624abec69b9e1a5e6c277750a77cf62f35a99ea98972201501859d330d1ddf0d4f825971d488ed4179943250f85a0aae2a4",
          "sha256": "7b48a3c8c4f040478c930ba10fed837c015cba5b7387d18b5216f91a25d3511f",
          "sha1": "95f71a2a87b2313e8c86044ff209d8a6b8f10b85",
          "md5": "d26457f475c56618cf2f83fe1145187d"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.ow2.asm",
          "module": "asm-tree",
          "version": {
            "requires": "9.7.1"
          }
        }
      ],
      "files": [
        {
          "name": "classpath-api-stubs-0.1.10-dust.jar",
          "url": "classpath-api-stubs-0.1.10-dust.jar",
          "size": 74942,
          "sha512": "02f82b0a76a7c7e240004bdeaf458624abec69b9e1a5e6c277750a77cf62f35a99ea98972201501859d330d1ddf0d4f825971d488ed4179943250f85a0aae2a4",
          "sha256": "7b48a3c8c4f040478c930ba10fed837c015cba5b7387d18b5216f91a25d3511f",
          "sha1": "95f71a2a87b2313e8c86044ff209d8a6b8f10b85",
          "md5": "d26457f475c56618cf2f83fe1145187d"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "classpath-api-stubs-0.1.10-dust-sources.jar",
          "url": "classpath-api-stubs-0.1.10-dust-sources.jar",
          "size": 12317,
          "sha512": "1c617bf5b7761f6043f65ac7c24aa3dc5ca14e46882924493a207f374078fe19e85c7d22b17a76e6986764957cd0247873d246b0f7c6499a4ddf38f4893d23a5",
          "sha256": "0c42e6671453e4b50a98014c65bc83f144d073b9d8c7931990a8d67e1cc3eeb1",
          "sha1": "8132aca75c47ca4e1f76d4e87c0ff9e331c74936",
          "md5": "feabf07e0e25e9780478390184ab3b1e"
        }
      ]
    }
  ]
}
