{
  "formatVersion": "1.1",
  "component": {
    "group": "net.msrandom",
    "module": "jvm-virtual-source-sets",
    "version": "1.3.5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.1.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "jvm-virtual-source-sets-1.3.5.jar",
          "url": "jvm-virtual-source-sets-1.3.5.jar",
          "size": 50299,
          "sha512": "dbd8baff3f0e064a181a86bcb2c3a7ca6933cca66f18faed59677f05d71c5e88ba3fc6463f6b5352586768b14c363087d8deaa06896ceb1f05aa60786dac326c",
          "sha256": "6c7f4b641c3b358bc27fcf71050c333f25dffae93fc3a9bb6aa904bfd3dbc7b7",
          "sha1": "50a79095293c3aa583cdfb84f09c649c714c0efe",
          "md5": "0e075ccc5cf811052a4ff76b624fd9fb"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "jvm-virtual-source-sets-1.3.5.jar",
          "url": "jvm-virtual-source-sets-1.3.5.jar",
          "size": 50299,
          "sha512": "dbd8baff3f0e064a181a86bcb2c3a7ca6933cca66f18faed59677f05d71c5e88ba3fc6463f6b5352586768b14c363087d8deaa06896ceb1f05aa60786dac326c",
          "sha256": "6c7f4b641c3b358bc27fcf71050c333f25dffae93fc3a9bb6aa904bfd3dbc7b7",
          "sha1": "50a79095293c3aa583cdfb84f09c649c714c0efe",
          "md5": "0e075ccc5cf811052a4ff76b624fd9fb"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "jvm-virtual-source-sets-1.3.5-sources.jar",
          "url": "jvm-virtual-source-sets-1.3.5-sources.jar",
          "size": 4299,
          "sha512": "fa1fafa6c6c945b14c8d87a28f475b4d3e0d06b913e53ee62ac5c07e19ea5d9b09f1499395560de944ac0d5a495d051eda843fa9d7a1dbf4179c69cff0d91d21",
          "sha256": "121166d1ea426466f21fe6e4671fd013fdb13b07a83752596a09ca7b15be9452",
          "sha1": "dede3f1ac9e2a928ebf25513493f020f4285bab6",
          "md5": "2b0cc2a710f069c2cc397b592d57642d"
        }
      ]
    }
  ]
}
