{
  "formatVersion": "1.1",
  "component": {
    "group": "net.msrandom",
    "module": "kmp-actual-stubs-compiler-plugin",
    "version": "0.1.0-dust",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.1.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "kmp-actual-stubs-compiler-plugin-0.1.0-dust.jar",
          "url": "kmp-actual-stubs-compiler-plugin-0.1.0-dust.jar",
          "size": 26556,
          "sha512": "ad238c2305c8f6a13a9a4153a812fbb04a1ad141e9ece025651345f43560f0c1814b85022622cdab966a1a89d61e8d1dedd2c3e24d652cb3b4de6559ee15ade0",
          "sha256": "6fce2f465af1ba2f9b3a0d2f526d0ee32195089c85409dd4383460b69d620a62",
          "sha1": "d5f1da258143693221113f05cb82ee2859228eff",
          "md5": "8fbd85f796d0119c50fccf4000fd04ce"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-compiler-embeddable"
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.0"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-compiler-embeddable",
          "version": {
            "requires": "2.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "kmp-actual-stubs-compiler-plugin-0.1.0-dust.jar",
          "url": "kmp-actual-stubs-compiler-plugin-0.1.0-dust.jar",
          "size": 26556,
          "sha512": "ad238c2305c8f6a13a9a4153a812fbb04a1ad141e9ece025651345f43560f0c1814b85022622cdab966a1a89d61e8d1dedd2c3e24d652cb3b4de6559ee15ade0",
          "sha256": "6fce2f465af1ba2f9b3a0d2f526d0ee32195089c85409dd4383460b69d620a62",
          "sha1": "d5f1da258143693221113f05cb82ee2859228eff",
          "md5": "8fbd85f796d0119c50fccf4000fd04ce"
        }
      ]
    }
  ]
}
