name: Publish Local

on:
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Set up JDK 17
        uses: actions/setup-java@v5
        with:
          java-version: 17
          distribution: 'adopt'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Checkout
        uses: actions/checkout@v5
        with:
          ref: maven-repo
          path: publish

      - name: Publish
        run: ./gradlew publishAllPublicationsToProjectRepository

      - name: Deploy to maven-repo branch
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: maven-repo
          publish_dir: publish